version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"              # Root directory (where your build.gradle is)
    schedule:
      interval: "weekly"        # Options: "daily", "weekly", "monthly"
      day: "tuesday"            # Optional: Pick a day
      time: "04:00"             # Optional: UTC time
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
