[versions]
# Mod Metadata
modVersion = "1.2.4"
mavenGroup = "mod.azure.iseelava"
modName = "iseelava"

# Toolchain and Environment
java = "25"
minecraft = "26.3"
pack = "[97, 1]"            # Resource Pack Version

# Fabric Components
loom = "1.18.2"            # Fabric Loom Version
fabric = "0.160.7+26.3"     # Fabric API Version
fabricLoader = "0.19.5"     # Fabric Loader Version

[libraries]
# Dependencies in the build.gradle
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric" }

[plugins]
# Plugin in the build.gradle
loomID = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
